export const REVIEWS = [
        {
            user: 'Yulia Yulia',
            id: '1',
            location: 'google',
            rating: '5',
            text: 'This is the best ever weed shop in Thailand! If you don’t believe me come and check it out yourself Amazing staff and BIG variety of products👍🏻',
        },
        {
            user: 'henry chilver',
            id: '2',
            location: 'google',
            rating: '5',
            text: 'Great dispensary! Would recommend! Can speak english and thai great staff!',
        },
        {
            user: 'SilentSal',
            id: '3',
            location: 'google',
            rating: '5',
            text: 'They have the highest quality stuff to smoke in the city for sure and the prices are good. Nice shop.',
        },
        {
            user: 'thisis.jessica chilver',
            id: '4',
            location: 'google',
            rating: '5',
            text: 'The best place for weed in pattaya city, outstanding service and amazing quality products !!!',
        },
        {
            user: 'Marco Yu',
            id: '5',
            location: 'google',
            rating: '5',
            text: 'Tried the Cannabis with very good quality under excellent service provided by the store!',
        },
        {
            user: 'Kaweetuch Sriboonruang',
            id: '6',
            location: 'google',
            rating: '5',
            text: 'Been around to many shops in Pattaya and I can say this place is the best. Lots of items and quality strains.',
        },
        {
            user: 'Fedor Bondarenko',
            id: '7',
            location: 'google',
            rating: '5',
            text: 'A lot of interesting strains, a lot of different equipment and accessories for smoking an very good prices!!!',
        },
    ]
